create Rental entity
Gamemod13/car-sharing-service pull request #4
Opened 2023-07-31 14:57 UTC by mykyta-udav

2023-07-31 15:15 UTC, Gamemod13 requested changes
Good, but I think it's better to remove @Accessors

2023-07-31 15:15 UTC, Gamemod13 commented on src/main/java/mate/academy/car/sharing/entity/Rental.java
> +@Accessors(chain = true)
@Accessors(chain = true) - is redundand in Entity, because Hibernate manage this entity, so we don't need a chain of setters

2023-07-31 15:37 UTC, Gamemod13 submitted a review, later dismissed

2023-07-31 17:18 UTC, ykhmaruk commented on src/main/java/mate/academy/car/sharing/entity/Rental.java
> +    private Car carId;
better to use  private Car car;
private User user;

2023-07-31 17:45 UTC, ykhmaruk approved these changes

2023-08-01 06:49 UTC, vika-trach approved these changes

2023-08-01 07:30 UTC, merged